# Generated by Django 5.1.5 on 2025-02-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_remove_supportvisibilite_occupe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplacement',
            name='date_debut',
            field=models.DateField(blank=True, help_text="Date de début de l'engagement", null=True),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='date_fin',
            field=models.DateField(blank=True, help_text="Date de fin de l'engagement", null=True),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='duree_engagement',
            field=models.PositiveIntegerField(blank=True, help_text="Durée de l'engagement en jours", null=True),
        ),
    ]
